name: 'Sync with registry'
description: 'Synchronize monorepo with registry'
inputs:
  monorepo_url:
    description: 'Git URL with monorepo'
    required: false
  update_all_workflows:
    description: 'Force updating all GHA workflow scripts'
    required: false
runs:
  using: 'docker'
  image: 'docker://ghcr.io/r-universe-org/sync'
  args:
    - ${{ inputs.monorepo_url }}
  env:
    UPDATE_ALL_WORKFLOWS: ${{ inputs.update_all_workflows }}
