name: 'Sync with registry'
description: 'Synchronize monorepo with registry'
inputs:
  monorepo_url:
    description: 'Git URL with monorepo'
    required: false
  quick:
    description: 'Use the new quick update'
    required: false
runs:
  using: 'docker'
  image: 'docker://ghcr.io/r-universe-org/sync'
  args:
    - ${{ inputs.monorepo_url }}
    - ${{ inputs.quick }}
